---
  - name: My first playbook to put it on git
    hosts: localhost
    connection: local
    become: true

    tasks:
      - name: Create a app directory
        ansible.builtin.file:
          path: /home/ubuntu/git-repo
          state: directory
          mode: '0777'

      - name: Add content in the new file
        ansible.builtin.copy:
          content: "Hello, i am going to push this file on git for practice. Thank you !!"
          dest: /home/ubuntu/git-repo/ansible-git.txt
          mode: '0666'
